"""
Configuration constants for the generic web crawler.
"""

import re

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
DEFAULT_OUTPUT = "downloaded_site"
DEFAULT_MAX_DEPTH = 0          # 0 = unlimited
DEFAULT_DELAY = 0.25           # seconds between requests

# ---------------------------------------------------------------------------
# Crawler tuning
# ---------------------------------------------------------------------------
REQUEST_TIMEOUT = 30
MAX_RETRIES = 3

# ---------------------------------------------------------------------------
# Soft-404 (false positive) detection
# ---------------------------------------------------------------------------
# Keywords commonly found in custom error / not-found pages.
SOFT_404_KEYWORDS = [
    "page not found",
    "página no encontrada",
    "pagina no encontrada",
    "no encontrado",
    "not found",
    "404",
    "error 404",
    "page doesn't exist",
    "page does not exist",
    "nothing found",
    "no existe",
    "no se encontró",
    "no se encontro",
    "the page you requested",
    "this page could not be found",
    "we couldn't find",
    "lo sentimos",
    "oops",
]

# When the soft-404 baseline is available, responses whose size is within
# this ratio of the baseline size are candidates for soft-404 comparison.
SOFT_404_SIZE_RATIO = 0.15

# Minimum number of matching keywords in the body to consider a response a
# soft-404 (when it also matches the baseline size).
SOFT_404_MIN_KEYWORD_HITS = 1

# ---------------------------------------------------------------------------
# WordPress discovery paths (auto-queued when WP is detected)
# ---------------------------------------------------------------------------
WP_DISCOVERY_PATHS = [
    # REST API
    "/wp-json/",
    "/wp-json/wp/v2/posts",
    "/wp-json/wp/v2/pages",
    "/wp-json/wp/v2/categories",
    "/wp-json/wp/v2/tags",
    "/wp-json/wp/v2/users",
    "/wp-json/wp/v2/media",
    "/wp-json/wp/v2/comments",
    # Sitemaps
    "/wp-sitemap.xml",
    "/wp-sitemap-posts-post-1.xml",
    "/wp-sitemap-posts-page-1.xml",
    "/wp-sitemap-taxonomies-category-1.xml",
    "/wp-sitemap-users-1.xml",
    "/sitemap.xml",
    "/sitemap_index.xml",
    # Feeds
    "/feed/",
    "/comments/feed/",
    "/feed/atom/",
    # Login / admin
    "/wp-login.php",
    "/wp-admin/",
    # Common files
    "/readme.html",
    "/license.txt",
    "/wp-includes/css/dist/block-library/style.min.css",
    "/wp-includes/js/jquery/jquery.min.js",
]

# ---------------------------------------------------------------------------
# Content types parsed for further links
# ---------------------------------------------------------------------------
CRAWLABLE_TYPES = {
    "text/html",
    "application/xhtml+xml",
    "application/javascript",
    "text/javascript",
    "text/css",
    "text/plain",
    "application/json",
    "application/xml",
    "text/xml",
    "application/rss+xml",
    "application/atom+xml",
    "application/x-httpd-php",
    "text/x-php",
    "application/php",
    "application/x-yaml",
    "text/yaml",
    "text/x-ini",
}

# ---------------------------------------------------------------------------
# Blocked URL patterns (dangerous / non-crawlable endpoints)
# ---------------------------------------------------------------------------
BLOCKED_PATH_RE = re.compile(
    r"(logout|signout|delete|remove|unsubscribe)\b",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Hidden / sensitive files to probe at every discovered directory
# ---------------------------------------------------------------------------
HIDDEN_FILE_PROBES = [
    # -- Apache / web server config --
    ".htaccess",
    ".htpasswd",
    ".htgroups",
    ".htdigest",
    "httpd.conf",
    "apache2.conf",
    "sites-enabled/default",
    "conf/httpd.conf",
    # -- Nginx --
    "nginx.conf",
    "conf.d/default.conf",
    "sites-available/default",
    # -- Environment / dotenv --
    ".env",
    ".env.local",
    ".env.production",
    ".env.development",
    ".env.staging",
    ".env.test",
    ".env.example",
    ".env.sample",
    ".env.bak",
    ".env.old",
    ".env.save",
    ".env.dist",
    ".env.defaults",
    ".env.dev",
    ".env.prod",
    # -- General config --
    ".config",
    ".cfg",
    ".hst",                # history files (browser, shell)
    "config.php",
    "config.php.bak",
    "config.php.old",
    "config.php.save",
    "config.php.swp",
    "config.php~",
    "config.inc.php",
    "config.inc",
    "config.yml",
    "config.yaml",
    "config.json",
    "config.xml",
    "config.ini",
    "config.toml",
    "config.rb",
    "config.py",
    "config.js",
    "config.ts",
    "config.bak",
    "config.old",
    "conf.ini",
    "app.config",
    "app.yaml",
    "app.yml",
    "app.json",
    "appsettings.json",
    "appsettings.Development.json",
    "appsettings.Production.json",
    # -- Git --
    ".git/config",
    ".git/HEAD",
    ".git/index",
    ".git/COMMIT_EDITMSG",
    ".git/description",
    ".git/info/exclude",
    ".git/logs/HEAD",
    ".git/packed-refs",
    ".gitignore",
    ".gitattributes",
    ".gitmodules",
    # -- SVN / Mercurial --
    ".svn/entries",
    ".svn/wc.db",
    ".hg/hgrc",
    ".hgignore",
    # -- OS metadata --
    ".DS_Store",
    "Thumbs.db",
    "Desktop.ini",
    "._metadata",
    # -- Microsoft / IIS --
    "web.config",
    "web.config.bak",
    "Web.Debug.config",
    "Web.Release.config",
    "Global.asax",
    "iisstart.htm",
    # -- WordPress --
    "wp-config.php",
    "wp-config.php.bak",
    "wp-config.php.old",
    "wp-config.php.save",
    "wp-config.php.swp",
    "wp-config.php.txt",
    "wp-config-sample.php",
    "wp-login.php",
    "wp-cron.php",
    "wp-settings.php",
    "wp-includes/version.php",
    "wp-admin/install.php",
    "wp-content/debug.log",
    "xmlrpc.php",
    "wp-trackback.php",
    "wp-links-opml.php",
    "wp-content/uploads/",
    "wp-content/plugins/",
    "wp-content/themes/",
    "wp-json/",
    "readme.html",
    # -- Joomla --
    "configuration.php",
    "configuration.php.bak",
    "configuration.php~",
    # -- Drupal --
    "settings.php",
    "settings.local.php",
    "sites/default/settings.php",
    # -- Laravel --
    "storage/logs/laravel.log",
    "artisan",
    ".env.backup",
    "bootstrap/cache/config.php",
    # -- Django / Python --
    "settings.py",
    "local_settings.py",
    "manage.py",
    "wsgi.py",
    "asgi.py",
    "celeryconfig.py",
    # -- Ruby / Rails --
    "database.yml",
    "database.yml.example",
    "secrets.yml",
    "credentials.yml.enc",
    "master.key",
    "Rakefile",
    # -- Docker --
    ".dockerignore",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "docker-compose.override.yml",
    "docker-compose.prod.yml",
    "docker-compose.dev.yml",
    ".docker/config.json",
    # -- CI/CD --
    ".travis.yml",
    ".circleci/config.yml",
    ".github/workflows/main.yml",
    ".github/workflows/ci.yml",
    ".gitlab-ci.yml",
    "Jenkinsfile",
    "azure-pipelines.yml",
    "bitbucket-pipelines.yml",
    "buildspec.yml",
    # -- Build / package managers --
    "Makefile",
    "CMakeLists.txt",
    "Gruntfile.js",
    "Gulpfile.js",
    "webpack.config.js",
    "rollup.config.js",
    "vite.config.js",
    "vite.config.ts",
    "nuxt.config.js",
    "nuxt.config.ts",
    "next.config.js",
    "next.config.mjs",
    "vue.config.js",
    "angular.json",
    "composer.json",
    "composer.lock",
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Gemfile",
    "Gemfile.lock",
    "requirements.txt",
    "requirements-dev.txt",
    "Pipfile",
    "Pipfile.lock",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "poetry.lock",
    "Cargo.toml",
    "Cargo.lock",
    "go.mod",
    "go.sum",
    "build.gradle",
    "build.gradle.kts",
    "pom.xml",
    "build.xml",
    "ivy.xml",
    "project.clj",
    "mix.exs",
    "rebar.config",
    "deno.json",
    "deno.lock",
    "bun.lockb",
    # -- Linting / formatting --
    ".babelrc",
    ".babelrc.json",
    "babel.config.js",
    "babel.config.json",
    ".eslintrc",
    ".eslintrc.json",
    ".eslintrc.js",
    ".eslintrc.yml",
    ".eslintignore",
    ".prettierrc",
    ".prettierrc.json",
    ".prettierignore",
    ".stylelintrc",
    ".stylelintrc.json",
    "tsconfig.json",
    "tsconfig.build.json",
    "jsconfig.json",
    ".browserslistrc",
    ".postcssrc",
    "postcss.config.js",
    "tailwind.config.js",
    "tailwind.config.ts",
    ".editorconfig",
    ".flake8",
    ".pylintrc",
    ".rubocop.yml",
    ".phpcs.xml",
    "phpunit.xml",
    "phpunit.xml.dist",
    "jest.config.js",
    "jest.config.ts",
    "vitest.config.ts",
    "karma.conf.js",
    ".mocharc.yml",
    "pytest.ini",
    "tox.ini",
    "mypy.ini",
    ".coveragerc",
    "codecov.yml",
    ".nycrc",
    # -- SEO / discovery --
    "robots.txt",
    "sitemap.xml",
    "sitemap_index.xml",
    "sitemap.xml.gz",
    "sitemap1.xml",
    "sitemap2.xml",
    "rss.xml",
    "feed.xml",
    "atom.xml",
    "crossdomain.xml",
    "clientaccesspolicy.xml",
    "browserconfig.xml",
    "manifest.json",
    "site.webmanifest",
    "favicon.ico",
    "apple-touch-icon.png",
    "ads.txt",
    "app-ads.txt",
    "sellers.json",
    # -- Security / well-known --
    "security.txt",
    ".well-known/security.txt",
    ".well-known/openid-configuration",
    ".well-known/assetlinks.json",
    ".well-known/apple-app-site-association",
    ".well-known/change-password",
    ".well-known/jwks.json",
    ".well-known/acme-challenge",
    # -- PHP --
    "phpinfo.php",
    "info.php",
    "test.php",
    "i.php",
    "pi.php",
    "php.ini",
    ".user.ini",
    "php.ini.bak",
    # -- Database --
    "backup.sql",
    "dump.sql",
    "db.sql",
    "database.sql",
    "data.sql",
    "mysql.sql",
    "export.sql",
    "backup.sql.gz",
    "backup.sql.bz2",
    "db.sqlite",
    "db.sqlite3",
    "database.sqlite",
    "database.sqlite3",
    "data.db",
    # -- Shell / system --
    ".bash_history",
    ".bashrc",
    ".bash_profile",
    ".profile",
    ".zshrc",
    ".zsh_history",
    ".sh_history",
    ".vimrc",
    ".viminfo",
    "crontab",
    "passwd",
    "shadow",
    # -- SSH / TLS keys & certs --
    ".ssh/authorized_keys",
    ".ssh/known_hosts",
    ".ssh/id_rsa",
    ".ssh/id_rsa.pub",
    ".ssh/id_ed25519",
    ".ssh/id_ed25519.pub",
    "id_rsa",
    "id_rsa.pub",
    "id_dsa",
    "id_dsa.pub",
    "server.key",
    "server.crt",
    "server.pem",
    "private.key",
    "private.pem",
    "public.key",
    "public.pem",
    "certificate.crt",
    "certificate.pem",
    "ca-bundle.crt",
    "ssl-cert-snakeoil.key",
    "ssl-cert-snakeoil.pem",
    "keystore.jks",
    "truststore.jks",
    ".p12",
    ".pfx",
    # -- Logs --
    "error_log",
    "error.log",
    "access_log",
    "access.log",
    "debug.log",
    "app.log",
    "application.log",
    "server.log",
    "install.log",
    "migration.log",
    "cron.log",
    "mail.log",
    "syslog",
    "messages",
    "npm-debug.log",
    "yarn-error.log",
    "yarn-debug.log",
    # -- Documentation --
    "README.md",
    "README.txt",
    "README.rst",
    "README.html",
    "CHANGELOG.md",
    "CHANGELOG.txt",
    "CHANGES.md",
    "HISTORY.md",
    "LICENSE",
    "LICENSE.txt",
    "LICENSE.md",
    "COPYING",
    "NOTICE",
    "CONTRIBUTING.md",
    "AUTHORS",
    "AUTHORS.md",
    "TODO.md",
    "TODO.txt",
    "humans.txt",
    "VERSION",
    "VERSION.txt",
    # -- Backup / temp / swap --
    "backup.tar",
    "backup.tar.gz",
    "backup.tgz",
    "backup.zip",
    "backup.rar",
    "backup.7z",
    "site.tar.gz",
    "www.tar.gz",
    "www.zip",
    "public.tar.gz",
    "public.zip",
    "htdocs.tar.gz",
    "old.zip",
    "archive.zip",
    "archive.tar.gz",
    "temp.zip",
    "test.zip",
    ".swp",
    ".swo",
    "~",
    # -- Cloud / serverless --
    "firebase.json",
    ".firebaserc",
    "now.json",
    "vercel.json",
    "netlify.toml",
    "amplify.yml",
    "serverless.yml",
    "serverless.yaml",
    "sam-template.yaml",
    "template.yaml",
    "cloudformation.yaml",
    "terraform.tfvars",
    "terraform.tfstate",
    "main.tf",
    "variables.tf",
    "outputs.tf",
    "ansible.cfg",
    "playbook.yml",
    "inventory",
    "hosts",
    "Vagrantfile",
    # -- API docs --
    "swagger.json",
    "swagger.yaml",
    "openapi.json",
    "openapi.yaml",
    "api-docs.json",
    "graphql",
    "graphql/schema",
    ".graphqlrc",
    ".graphqlrc.yml",
    # -- Misc application --
    "elmah.axd",
    "trace.axd",
    ".idea/workspace.xml",
    ".vscode/settings.json",
    ".vscode/launch.json",
    "nbproject/project.properties",
    ".project",
    ".classpath",
    ".settings/org.eclipse.core.resources.prefs",
    "bower.json",
    ".bowerrc",
    "Procfile",
    "Procfile.dev",
    "runtime.txt",
    "nixpacks.toml",
    ".node-version",
    ".nvmrc",
    ".python-version",
    ".ruby-version",
    ".java-version",
    ".tool-versions",
    ".npmrc",
    ".npmignore",
    ".yarnrc",
    ".yarnrc.yml",
    "lerna.json",
    "nx.json",
    "turbo.json",
    "renovate.json",
    ".renovaterc",
    "dependabot.yml",
    ".github/dependabot.yml",
]
