"""
Generic WAF (Web Application Firewall) detection.

Scans the response body for signatures of known WAF / security products:
Cloudflare, Wordfence, Sucuri, ModSecurity, Imperva / Incapsula, Akamai,
Shield Security, iThemes Security, SiteGround, and generic CAPTCHA tokens.

The :data:`WAF_SIGNATURES` dictionary is the canonical source of all
signatures used by the detection engine.
"""

from __future__ import annotations

from .base import BaseDetector

__all__ = ["WAFDetector", "WAF_SIGNATURES"]

WAF_SIGNATURES: dict[str, list[str]] = {
    "cloudflare": [
        "cf-mitigated",
        "attention required! | cloudflare",
        "cf-chl-bypass",
        "checking your browser",
        "_cf_chl_opt",
        "challenges.cloudflare.com",
    ],
    "wordfence": [
        "wordfence",
        "wfwaf-authcookie",
        "this site is protected by wordfence",
        "your access to this site has been limited",
        "generated by wordfence",
    ],
    "sucuri": [
        "sucuri",
        "x-sucuri-id",
        "sucuri-cloudproxy",
        "access denied - sucuri website firewall",
        "sucuri website firewall",
    ],
    "modsecurity": [
        "mod_security",
        "modsecurity",
        "not acceptable!",
        "noyb",
    ],
    "imperva": [
        "x-iinfo",
        "incapsula",
        "imperva",
        "visid_incap",
        "_incapsula_",
    ],
    "akamai": [
        "akamai",
        "akamaighost",
        "x-akamai-transformed",
        "ak_bmsc",
    ],
    "shield_security": [
        "icwp-wpsf",
        "shield security",
    ],
    "ithemes_security": [
        "itsec",
        "ithemes security",
        "solid security",
    ],
    "siteground": [
        "sg-captcha",
        "sgcaptcha",
        ".well-known/sgcaptcha",
    ],
    "captcha": [
        "captcha",
        "recaptcha",
        "hcaptcha",
        "g-recaptcha",
        "h-captcha",
        "cf-turnstile",
        "funcaptcha",
        "geetest",
        "please verify you are a human",
        "verificar que eres humano",
        "complete the security check",
    ],
}


class WAFDetector(BaseDetector):
    """Detect generic WAF or CAPTCHA protection on a page."""

    name = "waf"

    def detect(
        self,
        url: str,
        status_code: int,
        headers: dict,
        body: str,
    ) -> dict | None:
        if not body:
            return None
        body_lower = body.lower()
        for category, signatures in WAF_SIGNATURES.items():
            for sig in signatures:
                if sig.lower() in body_lower:
                    return {
                        "type": "waf",
                        "category": category,
                        "signature": sig,
                    }
        return None
