#!/usr/bin/env python3
"""LMSA Firmware Downloader — standalone, self-contained tool.

Downloads firmware files from lsa.lenovo.com / rsddownload-secure.lenovo.com
using a GUID + JWT captured from a live LMSA session (HTTPToolkit / Charles).

Two URL types are handled automatically:

  1. rsddownload-secure.lenovo.com (direct auth):
       GET https://rsddownload-secure.lenovo.com/<file.zip>
       Headers: Authorization: Bearer <jwt>  +  guid: <guid>
       → These are the URLs in download_links.txt.  A fresh JWT is required.

  2. Pre-signed S3 URLs (from getResource.jhtml):
       GET https://rsddownload-secure.lenovo.com/<file.zip>?X-Amz-Algorithm=…
       → No auth headers needed; URL itself contains AWS credentials.
       → The tool fetches fresh pre-signed URLs via getResource.jhtml.

When the JWT expires the tool exchanges the WUST (if provided) for a fresh
JWT automatically.

Usage::

    python downloader.py [--config config.ini] [--dry-run]

Requirements: Python 3.9+  and  pip install requests
"""

from __future__ import annotations

import argparse
import configparser
import sys
import time
import threading
import urllib.parse
import uuid
import json as _json
import re
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Optional

try:
    import requests
    from requests.adapters import HTTPAdapter
    from urllib3.util.retry import Retry
except ImportError:
    sys.exit(
        "ERROR: 'requests' is not installed.\n"
        "Run:  pip install requests\n"
        "   or pip install -r requirements.txt"
    )

# ============================================================================
# LMSA protocol constants
# Reverse-engineered from:
#   • Software Fix.exe.config
#   • lenovo.mbg.service.common.webservices.dll  (decompiled)
#   • lenovo.mbg.service.common.utilities.dll    (decompiled)
#   • Live HAR + download_links.txt (LMSA 7.5.4.2, 2026-03-04)
# ============================================================================

LMSA_BASE_URL  = "https://lsa.lenovo.com/Interface"
CLIENT_VERSION = "7.5.4.2"

# Endpoints confirmed from WebApiUrl.cs (decompiled) + live testing
_EP_INIT_TOKEN   = "/client/initToken.jhtml"
_EP_LOGIN_WUST   = "/user/lenovoIdLogin.jhtml"
_EP_RENEW_LINK   = "/client/renewFileLink.jhtml"     # fallback (404 on some servers)
_EP_GET_RESOURCE = "/rescueDevice/getResource.jhtml" # fresh pre-signed URLs
_EP_GET_MODELS   = "/rescueDevice/getModelNames.jhtml"

_CODE_OK          = "0000"
_AUTH_ERROR_CODES = frozenset({"401", "402", "403", "406"})

# Hosts where files are served via LMSA JWT auth headers
# (confirmed from download_links.txt + live CloudFront behaviour)
_S3_AUTH_HOSTS = frozenset({
    "rsddownload-secure.lenovo.com",
    "moto-rsd-prod-secure.s3.us-east-1.amazonaws.com",
    "moto-rsd-prod-secure.s3.amazonaws.com",
})

# HTTP headers for every LMSA API call (confirmed from HAR + decompile)
_API_HEADERS: dict[str, str] = {
    # httpWebRequest.UserAgent in decompiled source
    "User-Agent":    "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 "
                     "(KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36",
    "Content-Type":  "application/json",
    "Cache-Control": "no-store,no-cache",   # confirmed from HAR
    "Pragma":        "no-cache",
    "Request-Tag":   "lmsa",               # custom LMSA client tag
    "clientVersion": CLIENT_VERSION,
    "Connection":    "Close",              # KeepAlive=false in C# source
}

# Headers used when downloading files from rsddownload-secure.lenovo.com
# Confirmed from download_links.txt generated by crawler (2026-03-04)
_DL_HEADERS: dict[str, str] = {
    "User-Agent":                "Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) "
                                 "AppleWebKit/605.1.15 (KHTML, like Gecko) "
                                 "Version/17.6 Mobile/15E148 Safari/604.1",
    "Accept":                    "text/html,application/xhtml+xml,application/xml;"
                                 "q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language":           "en-US,en;q=0.9,es;q=0.8",
    "Cache-Control":             "no-cache",
    "Pragma":                    "no-cache",
    "Sec-Fetch-Dest":            "document",
    "Sec-Fetch-Mode":            "navigate",
    "Sec-Fetch-Site":            "none",
    "Sec-Fetch-User":            "?1",
    "Upgrade-Insecure-Requests": "1",
    "Request-Tag":               "lmsa",   # required for CloudFront auth check
}


# ============================================================================
# Colour helpers
# ============================================================================

_COLOUR = sys.stdout.isatty() and os.name != "nt"

def _c(code: str, t: str) -> str:
    return f"\033[{code}m{t}\033[0m" if _COLOUR else t

def _ok(t):   return _c("32", t)
def _warn(t): return _c("33", t)
def _err(t):  return _c("31", t)
def _info(t): return _c("36", t)
def _dim(t):  return _c("2",  t)


# ============================================================================
# URL helpers
# ============================================================================

def _host(url: str) -> str:
    return urllib.parse.urlparse(url).netloc.lower()

def _is_direct_auth(url: str) -> bool:
    """True for rsddownload-secure.lenovo.com URLs WITHOUT ?X-Amz- signing.

    These require  Authorization: Bearer <jwt>  +  guid: <guid>  headers.
    Confirmed from download_links.txt generated by crawler (2026-03-04).
    """
    if _host(url) not in _S3_AUTH_HOSTS:
        return False
    return "X-Amz-" not in url

def _is_presigned(url: str) -> bool:
    """True for AWS pre-signed URLs (contain ?X-Amz-Algorithm=…).

    Downloaded directly — no auth headers needed; credentials are in the URL.
    Obtained fresh via getResource.jhtml.
    """
    return _host(url) in _S3_AUTH_HOSTS and "X-Amz-" in url

def _strip_qs(url: str) -> str:
    p = urllib.parse.urlparse(url)
    return urllib.parse.urlunparse(p._replace(query="", fragment=""))

def _filename_from_url(url: str) -> str:
    path = urllib.parse.urlparse(url).path
    name = path.rstrip("/").rsplit("/", 1)[-1]
    return urllib.parse.unquote(name) if name else "download"


# ============================================================================
# LMSA API client
# ============================================================================

class LMSAClient:
    """Self-contained LMSA API client (all headers, body format, JWT rotation).

    RequestModel body (confirmed from decompiled RequestModel.cs):
        { client: {version}, language, windowsInfo, dparams: {..., guid} }

    Auth headers (confirmed from WebApiHttpRequest.RequestBase, decompiled):
        guid:          <GUID>
        Authorization: Bearer <JWT>

    JWT rotation: server echoes GUID in response header when it issues a new
    JWT in the Authorization response header.  Confirmed from source:
        if (Guid_header == GUID && Authorization_header != "")
            JWT_TOKEN = Authorization_header;
    """

    def __init__(
        self,
        guid: str,
        jwt: str,
        wust: str = "",
        base_url: str = LMSA_BASE_URL,
        verify_ssl: bool = True,
    ) -> None:
        self.guid      = guid.strip().lower()
        self._jwt      = jwt.strip().removeprefix("Bearer ").strip()
        self._wust     = wust.strip()
        self.base_url  = base_url.rstrip("/")
        self._verify   = verify_ssl
        self._lock     = threading.Lock()
        self._refreshing = False

        self._sess = requests.Session()
        self._sess.headers.update(_API_HEADERS)
        self._sess.verify = verify_ssl
        _retry = Retry(total=3, backoff_factor=0.5,
                       status_forcelist=(), allowed_methods={"POST"})
        self._sess.mount("https://", HTTPAdapter(max_retries=_retry))
        self._sess.mount("http://",  HTTPAdapter(max_retries=_retry))

    def current_jwt(self) -> str:
        return self._jwt

    def _auth_headers(self) -> dict[str, str]:
        """Per-request auth headers (guid + Authorization: Bearer <jwt>)."""
        hdrs: dict[str, str] = {"guid": self.guid}
        if self._jwt:
            hdrs["Authorization"] = f"Bearer {self._jwt}"
        return hdrs

    def _build_body(self, params: dict) -> dict:
        dp = dict(params)
        dp.setdefault("guid", self.guid)
        return {
            "client":      {"version": CLIENT_VERSION},
            "language":    "en-US",
            "windowsInfo": "Microsoft Windows 11 Pro, x64-based PC",
            "dparams":     dp,
        }

    def _rotate_jwt(self, resp: requests.Response) -> None:
        """Rotate JWT from response headers if server issues a new one."""
        if resp.headers.get("Guid", "").lower() == self.guid:
            new_auth = resp.headers.get("Authorization", "")
            if new_auth:
                new_jwt = new_auth.removeprefix("Bearer ").strip()
                if new_jwt and new_jwt != self._jwt:
                    self._jwt = new_jwt

    def post(self, endpoint: str, params: dict, *, _retrying: bool = False) -> Optional[dict]:
        """POST a RequestModel to *endpoint* and return parsed JSON."""
        body = self._build_body(params)
        url  = self.base_url + endpoint
        try:
            resp = self._sess.post(url, json=body,
                                   headers=self._auth_headers(), timeout=30)
        except requests.RequestException as exc:
            print(_warn(f"  [API] {endpoint}: {exc}"))
            return None

        self._rotate_jwt(resp)

        if resp.status_code == 401 and not _retrying:
            if self._refresh_jwt():
                return self.post(endpoint, params, _retrying=True)
            return None

        if resp.status_code != 200:
            print(_warn(f"  [API] {endpoint} → HTTP {resp.status_code}"))
            return None

        try:
            data = resp.json()
        except ValueError:
            return None

        code = data.get("code", "")
        if code in _AUTH_ERROR_CODES and not _retrying:
            print(_warn(f"  [API] Auth error {code!r} on {endpoint} — refreshing JWT …"))
            if self._refresh_jwt():
                return self.post(endpoint, params, _retrying=True)

        return data

    # ------------------------------------------------------------------
    # JWT refresh via WUST
    # ------------------------------------------------------------------

    def _refresh_jwt(self) -> bool:
        """Exchange WUST → fresh JWT via /user/lenovoIdLogin.jhtml.

        Confirmed from decompiled Software Fix.exe (LenovoIdLoginService):
          • author=false → NO guid/Authorization request headers
          • dparams: {wust: <WUST>, guid: <GUID>}
          • JWT arrives in "Authorization" response header when server echoes
            our GUID in the "Guid" response header
        """
        if not self._wust:
            print(_err(
                "  [auth] JWT expired and no WUST provided.\n"
                "         Add  wust = <your-wust>  to [auth] in config.ini"
            ))
            return False

        with self._lock:
            if self._refreshing:
                return bool(self._jwt)
            self._refreshing = True

        try:
            url = self.base_url + _EP_LOGIN_WUST
            body = {
                "client":      {"version": CLIENT_VERSION},
                "dparams":     {"wust": self._wust, "guid": self.guid},
                "language":    "en-US",
                "windowsInfo": "Microsoft Windows 11 Pro, x64-based PC",
            }
            print(_info("  [auth] Exchanging WUST for fresh JWT …"))
            r = self._sess.post(url, json=body, headers=_API_HEADERS, timeout=30)

            guid_resp = r.headers.get("Guid", "").lower()
            auth_resp = r.headers.get("Authorization", "")
            jwt: Optional[str] = None
            if guid_resp == self.guid and auth_resp:
                jwt = auth_resp.removeprefix("Bearer ").strip()
            elif auth_resp.startswith("Bearer "):
                jwt = auth_resp[len("Bearer "):]

            try:
                data = r.json()
            except ValueError:
                print(_err("  [auth] Non-JSON from lenovoIdLogin"))
                return False

            code = data.get("code", "")
            if code == "402":
                print(_err("  [auth] ✗ WUST expired — capture a fresh WUST"))
                return False
            if code not in (_CODE_OK, ""):
                print(_err(f"  [auth] ✗ lenovoIdLogin error {code!r}"))
                return False

            if not jwt:
                content = data.get("content") or data.get("data") or {}
                if isinstance(content, dict):
                    jwt = content.get("token") or content.get("jwt")

            if jwt:
                self._jwt = jwt
                print(_ok("  [auth] ✓ JWT refreshed via WUST"))
                return True

            print(_warn("  [auth] lenovoIdLogin ok but no JWT in response"))
            return False
        finally:
            with self._lock:
                self._refreshing = False

    # ------------------------------------------------------------------
    # initToken
    # ------------------------------------------------------------------

    def init_token(self) -> None:
        """Register GUID with the LMSA server (initToken.jhtml).

        Confirmed from ApiBaseService.InitTokenAsync (decompiled):
          Called once at session start to bind the GUID server-side.
          Non-fatal if it fails (endpoint returns 404 on some server versions).
        """
        data = self.post(_EP_INIT_TOKEN, {})
        if data and data.get("code") == _CODE_OK:
            print(_ok("  [auth] ✓ GUID registered (initToken)"))
        else:
            code = (data or {}).get("code", "no response")
            print(_dim(f"  [auth] initToken: {code!r} (non-fatal, continuing)"))

    # ------------------------------------------------------------------
    # Fresh pre-signed URL via getResource (for models without demogb)
    # ------------------------------------------------------------------

    def get_presigned_url(self, base_url: str) -> Optional[str]:
        """Get a fresh pre-signed S3 URL for a known model via getResource.

        Extracts the model number from *base_url*'s filename, queries
        getResource for multiple countries, and returns the first fresh
        pre-signed URL whose S3 path matches *base_url*.

        Confirmed working: getResource returns ?X-Amz-signed URLs directly.
        """
        fname = urllib.parse.urlparse(base_url).path.rsplit("/", 1)[-1]
        m = re.search(r"(XT\d{4}-?\d?)", fname, re.I)
        if not m:
            return None
        model_hint = m.group(1).upper()

        countries = ("Mexico", "US", "Brazil", "Argentina", "Colombia",
                     "India", "Germany", "UK", "China", "France", "Spain")
        target_path = urllib.parse.urlparse(base_url).path

        for country in countries:
            mn_data = self.post(_EP_GET_MODELS,
                                {"country": country, "category": "Phone"})
            if not mn_data or mn_data.get("code") != _CODE_OK:
                continue
            content = mn_data.get("content") or {}
            all_m = (content.get("models") or []) + (content.get("moreModels") or [])
            match = next(
                (m for m in all_m
                 if model_hint in (m.get("modelName") or "").upper()),
                None,
            )
            if not match:
                continue

            res_data = self.post(_EP_GET_RESOURCE, {
                "modelName":  match.get("modelName", ""),
                "marketName": match.get("marketName", ""),
                "country":    country,
            })
            if not res_data or res_data.get("code") != _CODE_OK:
                continue

            items = res_data.get("content") or []
            if not isinstance(items, list):
                items = [items] if items else []

            for item in items:
                for key in ("romResource", "toolResource", "otaResource",
                            "countryCodeResource"):
                    res = item.get(key)
                    if isinstance(res, dict):
                        uri = res.get("uri", "")
                        if uri and urllib.parse.urlparse(uri).path == target_path:
                            print(_info(
                                f"  [presign] ✓ Fresh URL via getResource "
                                f"({match.get('modelName')}, {country})"
                            ))
                            return uri
            break  # model found in this country — stop
        return None


# ============================================================================
# URL manifest parser — supports all crawler output formats
# ============================================================================

_URL_RE    = re.compile(r"https?://\S+", re.IGNORECASE)
_HEADER_RE = re.compile(r"-H\s+['\"]([^:\"']+):\s*([^\"']+)['\"]")


def _parse_urls_file(path: Path) -> list[tuple[str, str, dict[str, str]]]:
    """Load URLs from any manifest file the crawler produces.

    Returns list of  (url, filename, extra_headers)  triples.

    extra_headers is populated from download_links.txt curl -H entries:
    they contain the Authorization + guid from the crawl session that must
    be replaced with fresh credentials at download time.

    Supported formats
    -----------------
    1. ``<url>\\t<filename>``  — lmsa_firmware_urls.txt / lmsa_rom_urls.txt
    2. Curl commands           — download_links.txt  (headers extracted)
    3. Plain one-URL-per-line
    """
    if not path.is_file():
        print(_warn(f"  URL file not found: {path}"))
        return []

    triples: list[tuple[str, str, dict[str, str]]] = []
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        lines = fh.readlines()

    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1

        if not line or line.startswith("#"):
            continue

        # ── curl block from download_links.txt ───────────────────────────
        if line.startswith("curl "):
            # Collect continuation lines
            block = line
            while block.endswith("\\") and i < len(lines):
                block = block[:-1] + lines[i].strip()
                i += 1

            # Extract URL (last quoted arg)
            urls_in_block = _URL_RE.findall(block)
            if not urls_in_block:
                continue
            url = urls_in_block[-1].rstrip("'\"")

            # Extract all -H headers (will be replaced with fresh jwt/guid)
            hdrs: dict[str, str] = {}
            for name, val in _HEADER_RE.findall(block):
                hdrs[name.strip()] = val.strip()

            fname = _filename_from_url(url)
            triples.append((url, fname, hdrs))
            continue

        # ── Tab-separated: URL <TAB> filename ────────────────────────────
        if "\t" in line:
            url, _, fname = line.partition("\t")
            url   = url.strip()
            fname = fname.strip() or _filename_from_url(url)
            if url.startswith("http"):
                triples.append((url, fname, {}))
            continue

        # ── Plain URL ─────────────────────────────────────────────────────
        for m in _URL_RE.finditer(line):
            url = m.group(0).rstrip("'\"\\,;")
            if url:
                triples.append((url, _filename_from_url(url), {}))

    # Deduplicate by base URL preserving order
    seen: set[str] = set()
    unique: list[tuple[str, str, dict[str, str]]] = []
    for url, fname, hdrs in triples:
        b = _strip_qs(url)
        if b not in seen:
            seen.add(b)
            unique.append((url, fname, hdrs))
    return unique


# ============================================================================
# Downloader
# ============================================================================

class Downloader:
    """Download firmware files with automatic auth-header injection.

    Two download strategies (selected per URL):

    A) Direct auth  (rsddownload-secure.lenovo.com, no ?X-Amz- in URL):
         GET <url>  with  Authorization: Bearer <fresh_jwt>  +  guid: <guid>
         Confirmed from download_links.txt generated by crawler.

    B) Pre-signed   (any host, URL contains ?X-Amz-Algorithm=…):
         GET <url>  — credentials embedded in URL, no headers needed.
         If URL expired (403) → call getResource.jhtml to get fresh URL.
    """

    def __init__(
        self,
        client: LMSAClient,
        output_dir: Path,
        workers: int = 4,
        retries: int = 3,
        resume:  bool = True,
        verify_ssl: bool = True,
    ) -> None:
        self._client  = client
        self._out     = output_dir
        self._workers = max(1, workers)
        self._retries = max(1, retries)
        self._resume  = resume

        self._sess = requests.Session()
        self._sess.verify = verify_ssl
        dl_retry = Retry(total=retries, backoff_factor=1.0,
                         status_forcelist={500, 502, 503, 504},
                         allowed_methods={"GET", "HEAD"})
        self._sess.mount("https://", HTTPAdapter(max_retries=dl_retry))
        self._sess.mount("http://",  HTTPAdapter(max_retries=dl_retry))

    def _dl_headers(self, url: str) -> dict[str, str]:
        """Build download headers for *url*.

        For direct-auth S3 URLs → inject fresh JWT + guid.
        For pre-signed / public URLs → minimal headers only.
        """
        hdrs = dict(_DL_HEADERS)
        if _is_direct_auth(url):
            hdrs["Authorization"] = f"Bearer {self._client.current_jwt()}"
            hdrs["guid"]          = self._client.guid
        return hdrs

    def _resolve_url(self, url: str) -> str:
        """Return a ready-to-download URL.

        • Direct-auth (rsddownload-secure, no ?X-Amz-): URL stays the same,
          fresh JWT will be injected in headers at download time.
        • Pre-signed (URL has ?X-Amz-): URL already has credentials, but if
          it expired (403) we fetch a fresh URL via getResource.jhtml.
        • Public (download.lenovo.com, etc.): no change.
        """
        if _is_direct_auth(url):
            return url  # auth via headers, not URL params
        if _is_presigned(url):
            # will get fresh URL on 403 in _download_one
            return url
        return url  # public

    def _download_one(
        self,
        url: str,
        name: str,
        extra_hdrs: dict[str, str],
    ) -> tuple[str, bool, str]:
        """Download *url* → output_dir/name.  Returns (name, ok, message)."""
        dest = self._out / name
        dest.parent.mkdir(parents=True, exist_ok=True)

        dl_url = self._resolve_url(url)

        # Resume: check partial file
        resume_pos = 0
        if self._resume and dest.exists() and dest.stat().st_size > 0:
            resume_pos = dest.stat().st_size
            try:
                h = dict(self._dl_headers(dl_url))
                head = self._sess.head(dl_url, headers=h,
                                       timeout=15, allow_redirects=True)
                total = int(head.headers.get("Content-Length", 0))
                if total and resume_pos >= total:
                    return name, True, "already complete"
            except Exception:
                resume_pos = 0

        downloaded = resume_pos

        for attempt in range(1, self._retries + 1):
            hdrs = dict(self._dl_headers(dl_url))
            if resume_pos:
                hdrs["Range"] = f"bytes={resume_pos}-"
            mode = "ab" if resume_pos else "wb"

            try:
                with self._sess.get(
                    dl_url, headers=hdrs, stream=True,
                    timeout=(15, 600), allow_redirects=True,
                ) as resp:
                    if resp.status_code == 416:
                        return name, True, "already complete (416)"

                    # 403 on pre-signed URL → try fresh URL from getResource
                    if resp.status_code == 403 and _is_presigned(dl_url):
                        if attempt < self._retries:
                            fresh = self._client.get_presigned_url(_strip_qs(dl_url))
                            if fresh:
                                dl_url = fresh
                            continue

                    # 403 on direct-auth URL → JWT may be expired, refresh
                    if resp.status_code == 403 and _is_direct_auth(dl_url):
                        if attempt < self._retries and self._client._wust:
                            self._client._refresh_jwt()
                            continue
                        return name, False, (
                            "HTTP 403 — JWT expired. "
                            "Capture fresh GUID+JWT from HTTPToolkit and update config.ini"
                        )

                    if resp.status_code not in (200, 206):
                        msg = f"HTTP {resp.status_code}"
                        if attempt < self._retries:
                            time.sleep(2 ** attempt)
                            continue
                        return name, False, msg

                    with dest.open(mode) as fh:
                        for chunk in resp.iter_content(1 << 16):
                            if chunk:
                                fh.write(chunk)
                                downloaded += len(chunk)

                    return name, True, f"{downloaded / 1_048_576:.1f} MB"

            except requests.RequestException as exc:
                if attempt < self._retries:
                    time.sleep(2 ** attempt)
                else:
                    return name, False, str(exc)

        return name, False, "max retries exceeded"

    def run(self, triples: list[tuple[str, str, dict[str, str]]]) -> None:
        """Download all  (url, filename, extra_headers)  triples."""
        self._out.mkdir(parents=True, exist_ok=True)
        total = len(triples)
        ok_n  = 0
        failed: list[str] = []

        print(f"\n{_info('Downloading')} {total} file(s) → {self._out}/")
        print(f"Workers: {self._workers}  Retries: {self._retries}  Resume: {self._resume}\n")

        done = 0
        with ThreadPoolExecutor(max_workers=self._workers) as pool:
            futs = {
                pool.submit(self._download_one, u, n, h): n
                for u, n, h in triples
            }
            for fut in as_completed(futs):
                done += 1
                name, success, msg = fut.result()
                tag = f"[{done:>4}/{total}]"
                if success:
                    ok_n += 1
                    print(f"{tag} {_ok('✓')} {name}  {_dim(f'({msg})')}")
                else:
                    failed.append(name)
                    print(f"{tag} {_err('✗')} {name}  — {_err(msg)}")

        print(f"\n{'─'*62}")
        print(f"Result: {_ok(str(ok_n))} succeeded  /  "
              f"{_err(str(len(failed)))} failed  /  {total} total")
        if failed:
            print(_warn("\nFailed files:"))
            for f in failed:
                print(f"  • {f}")
        print()


# ============================================================================
# Config helpers
# ============================================================================

def _load_config(path: Path) -> configparser.ConfigParser:
    cfg = configparser.ConfigParser(inline_comment_prefixes=(";", "#"))
    cfg.read(path, encoding="utf-8")
    return cfg

def _get(cfg: configparser.ConfigParser, s: str, k: str, fb: str = "") -> str:
    try:
        return cfg.get(s, k).strip()
    except (configparser.NoSectionError, configparser.NoOptionError):
        return fb


# ============================================================================
# Entry point
# ============================================================================

def main() -> None:
    ap = argparse.ArgumentParser(
        description="LMSA Firmware Downloader — downloads firmware using fresh GUID+JWT.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--config", "-c", default="config.ini",
                    help="Path to config.ini")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print resolved info without downloading")
    ap.add_argument("--output", "-o", default="",
                    help="Override output directory")
    ap.add_argument("--workers", "-w", type=int, default=0,
                    help="Override parallel worker count (0 = use config)")
    args = ap.parse_args()

    config_path = Path(args.config).resolve()
    if not config_path.is_file():
        sys.exit(f"ERROR: config file not found: {config_path}")

    cfg        = _load_config(config_path)
    config_dir = config_path.parent

    # ── Auth ─────────────────────────────────────────────────────────────────
    lmsa_jwt_raw = _get(cfg, "auth", "lmsa_jwt")
    guid_raw     = _get(cfg, "auth", "guid")
    jwt_raw      = _get(cfg, "auth", "jwt")
    wust_raw     = _get(cfg, "auth", "wust")

    # Support GUID:JWT combined format (same as LMSA_JWT workflow input)
    if lmsa_jwt_raw and ":" in lmsa_jwt_raw:
        guid_raw, _, jwt_raw = lmsa_jwt_raw.partition(":")

    def _is_set(v: str) -> bool:
        return bool(v) and not v.upper().startswith("PASTE_") \
               and not v.upper().startswith("YOUR_")

    if not _is_set(guid_raw) or not _is_set(jwt_raw):
        sys.exit(
            "ERROR: GUID and JWT are required.\n\n"
            "Option A — combined GUID:JWT format:\n"
            "  [auth]\n"
            "  lmsa_jwt = 3adf1304-8a70-4352-b687-8eddcef6b7d1:dcwyMSw…\n\n"
            "Option B — separate fields:\n"
            "  [auth]\n"
            "  guid = 3adf1304-8a70-4352-b687-8eddcef6b7d1\n"
            "  jwt  = dcwyMSw…\n\n"
            "Add  wust = …  to enable automatic JWT refresh when it expires.\n\n"
            "Capture GUID and JWT from a running LMSA session via HTTPToolkit."
        )

    guid       = guid_raw.strip()
    jwt        = jwt_raw.strip()
    wust       = wust_raw.strip()
    base_url   = _get(cfg, "auth", "base_url", LMSA_BASE_URL)
    verify_ssl = cfg.getboolean("auth", "verify_ssl", fallback=True)

    # ── Settings ──────────────────────────────────────────────────────────────
    output_dir = Path(
        args.output or _get(cfg, "settings", "output_dir", "downloads")
    )
    if not output_dir.is_absolute():
        output_dir = config_dir / output_dir

    workers = args.workers or cfg.getint("settings", "workers", fallback=4)
    retries = cfg.getint("settings", "retries", fallback=3)
    resume  = cfg.getboolean("settings", "resume", fallback=True)

    # ── URLs ──────────────────────────────────────────────────────────────────
    triples: list[tuple[str, str, dict[str, str]]] = []

    urls_file_str = _get(cfg, "urls", "urls_file")
    if urls_file_str:
        uf = Path(urls_file_str)
        if not uf.is_absolute():
            uf = config_dir / uf
        loaded = _parse_urls_file(uf)
        print(f"Loaded {len(loaded)} URL(s) from {uf.name}" if loaded
              else _warn(f"No URLs found in {uf}"))
        triples.extend(loaded)

    # Inline urls: url_1 = …, url_2 = …
    if cfg.has_section("urls"):
        for key, val in cfg.items("urls"):
            if key.startswith("url") and key != "urls_file":
                url = val.strip()
                if url.startswith("http"):
                    triples.append((url, _filename_from_url(url), {}))

    if not triples:
        sys.exit(
            "ERROR: No URLs to download.\n"
            "Set  [urls] urls_file = lmsa_firmware_urls.txt  in config.ini\n"
            "  or set  [urls] urls_file = download_links.txt\n"
            "  or add  url_1 = https://…"
        )

    # Deduplicate
    seen_b: set[str] = set()
    unique: list[tuple[str, str, dict[str, str]]] = []
    for u, n, h in triples:
        b = _strip_qs(u)
        if b not in seen_b:
            seen_b.add(b)
            unique.append((u, n, h))
    triples = unique

    # ── Banner ────────────────────────────────────────────────────────────────
    s3_auth_count   = sum(1 for u, _, _ in triples if _is_direct_auth(u))
    presigned_count = sum(1 for u, _, _ in triples if _is_presigned(u))
    public_count    = len(triples) - s3_auth_count - presigned_count

    print(f"\n{'═'*62}")
    print(f"  LMSA Firmware Downloader")
    print(f"{'─'*62}")
    print(f"  Config  : {config_path}")
    print(f"  API     : {base_url}")
    print(f"  GUID    : {guid}")
    print(f"  JWT     : {jwt[:20]}…")
    if wust:
        print(f"  WUST    : {wust[:20]}…  (JWT auto-refresh enabled)")
    print(f"  Output  : {output_dir}")
    print(f"  URLs    : {len(triples)}  "
          f"(direct-auth:{s3_auth_count}  presigned:{presigned_count}  public:{public_count})")
    if args.dry_run:
        print(f"  Mode    : {_warn('DRY RUN — no files will be downloaded')}")
    print(f"{'═'*62}\n")

    # ── Build client and register GUID ────────────────────────────────────────
    client = LMSAClient(guid=guid, jwt=jwt, wust=wust,
                        base_url=base_url, verify_ssl=verify_ssl)
    client.init_token()

    # ── Dry run ───────────────────────────────────────────────────────────────
    if args.dry_run:
        print(_info("[dry-run] URL analysis:"))
        for url, name, hdrs in triples:
            if _is_direct_auth(url):
                kind = _info("direct-auth")
                note = "needs fresh JWT+GUID in headers"
            elif _is_presigned(url):
                kind = _ok("pre-signed")
                note = "credentials in URL"
            else:
                kind = _ok("public")
                note = "no auth needed"
            print(f"  [{kind}] {name}")
            print(f"           {url[:80]}…" if len(url) > 80 else f"           {url}")
            print(f"           {_dim(note)}")
        return

    # ── Download ──────────────────────────────────────────────────────────────
    Downloader(
        client=client,
        output_dir=output_dir,
        workers=workers,
        retries=retries,
        resume=resume,
        verify_ssl=verify_ssl,
    ).run(triples)


if __name__ == "__main__":
    main()
