"""
crawl4ai.extensions.detection – WAF / CAPTCHA / soft-404 / WordPress detection.

Ported from the ``web_crawler.detection`` package (originally split across
``base.py``, ``cloudflare.py``, ``siteground.py``, ``soft404.py``, ``waf.py``,
and ``wordpress.py``).  All classes and the ``detect_all`` registry function
are merged into this single self-contained module so that no imports from
``web_crawler`` are required.
"""

from __future__ import annotations

import hashlib
import re
from abc import ABC, abstractmethod

# ---------------------------------------------------------------------------
# WAF_SIGNATURES – inlined from web_crawler.config.settings
# ---------------------------------------------------------------------------

WAF_SIGNATURES: dict[str, list[str]] = {
    "cloudflare": [
        "cf-mitigated",
        "attention required! | cloudflare",
        "cf-chl-bypass",
        "checking your browser",
        "_cf_chl_opt",
        "challenges.cloudflare.com",
    ],
    "wordfence": [
        "wordfence",
        "wfwaf-authcookie",
        "this site is protected by wordfence",
        "your access to this site has been limited",
        "generated by wordfence",
    ],
    "sucuri": [
        "sucuri",
        "x-sucuri-id",
        "sucuri-cloudproxy",
        "access denied - sucuri website firewall",
        "sucuri website firewall",
    ],
    "modsecurity": [
        "mod_security",
        "modsecurity",
        "not acceptable!",
        "noyb",
    ],
    "imperva": [
        "x-iinfo",
        "incapsula",
        "imperva",
        "visid_incap",
        "_incapsula_",
    ],
    "akamai": [
        "akamai",
        "akamaighost",
        "x-akamai-transformed",
        "ak_bmsc",
    ],
    "shield_security": [
        "icwp-wpsf",
        "shield security",
    ],
    "ithemes_security": [
        "itsec",
        "ithemes security",
        "solid security",
    ],
    "siteground": [
        "sg-captcha",
        "sgcaptcha",
        ".well-known/sgcaptcha",
    ],
    "captcha": [
        "captcha",
        "recaptcha",
        "hcaptcha",
        "g-recaptcha",
        "h-captcha",
        "cf-turnstile",
        "funcaptcha",
        "geetest",
        "please verify you are a human",
        "verificar que eres humano",
        "complete the security check",
    ],
}

# ---------------------------------------------------------------------------
# BaseDetector
# ---------------------------------------------------------------------------


class BaseDetector(ABC):
    """Detects a specific technology or protection on a web page.

    Subclasses implement :meth:`detect` which inspects the HTTP response
    (status code, headers, body) and returns a detection dict when the
    technology is found, or ``None`` otherwise.
    """

    name: str = ""

    @abstractmethod
    def detect(
        self,
        url: str,
        status_code: int,
        headers: dict,
        body: str,
    ) -> dict | None:
        """Check whether this technology is present.

        Returns
        -------
        dict | None
            A dict with at least ``{"type": "<name>", ...}`` on detection,
            or ``None`` when not detected.
        """
        ...


# ---------------------------------------------------------------------------
# CloudflareDetector
# ---------------------------------------------------------------------------


class CloudflareDetector(BaseDetector):
    """Detect Cloudflare Managed Challenge (JS challenge / turnstile)."""

    name = "cloudflare"

    _CF_SIGNATURES = (
        "cf-mitigated",
        "cf_chl_opt",
        "challenges.cloudflare.com",
        "cf-browser-verification",
        "cf-spinner-please-wait",
        "Checking your browser",
        "Enable JavaScript and cookies to continue",
    )

    def detect(
        self,
        url: str,
        status_code: int,
        headers: dict,
        body: str,
    ) -> dict | None:
        # Check headers first (cheapest)
        if headers.get("cf-mitigated") == "challenge":
            return {"type": "cloudflare", "method": "header"}
        server = headers.get("server", "").lower()
        if "cloudflare" in server and status_code == 403:
            body_lower = body.lower() if body else ""
            for sig in self._CF_SIGNATURES:
                if sig.lower() in body_lower:
                    return {"type": "cloudflare", "method": "body", "signature": sig}
        return None


# ---------------------------------------------------------------------------
# SiteGroundDetector
# ---------------------------------------------------------------------------


class SiteGroundDetector(BaseDetector):
    """Detect SiteGround Security CAPTCHA (proof-of-work challenge)."""

    name = "siteground"

    _SG_SIGNATURES = (
        "sg-captcha-form",
        "sg_captcha_challenge",
        "<input name=\"sg-bypass-key\"",
    )

    def detect(
        self,
        url: str,
        status_code: int,
        headers: dict,
        body: str,
    ) -> dict | None:
        if not body:
            return None
        for sig in self._SG_SIGNATURES:
            if sig in body:
                return {"type": "siteground", "signature": sig}
        return None


# ---------------------------------------------------------------------------
# WAFDetector
# ---------------------------------------------------------------------------


class WAFDetector(BaseDetector):
    """Detect generic WAF or CAPTCHA protection on a page."""

    name = "waf"

    def detect(
        self,
        url: str,
        status_code: int,
        headers: dict,
        body: str,
    ) -> dict | None:
        if not body:
            return None
        body_lower = body.lower()
        for category, signatures in WAF_SIGNATURES.items():
            for sig in signatures:
                if sig.lower() in body_lower:
                    return {
                        "type": "waf",
                        "category": category,
                        "signature": sig,
                    }
        return None


# ---------------------------------------------------------------------------
# Soft404Detector
# ---------------------------------------------------------------------------

# Keywords commonly found in custom 404 pages
_SOFT404_KEYWORDS = (
    "page not found", "404 not found", "not found",
    "does not exist", "no longer available",
    "we couldn't find", "could not be found",
    "page you requested", "page you are looking for",
    "nothing here", "oops",
)

_TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.DOTALL)


class Soft404Detector(BaseDetector):
    """Detect soft-404 pages (200 status but actually a 'not found' page)."""

    name = "soft404"

    def __init__(self) -> None:
        self._baseline_hash: str | None = None
        self._baseline_size: int | None = None

    def set_baseline(self, body: str) -> None:
        """Set the baseline fingerprint from a known-404 page."""
        data = body.encode("utf-8", errors="replace")
        self._baseline_hash = hashlib.sha256(data).hexdigest()[:16]
        self._baseline_size = len(data)

    def detect(
        self,
        url: str,
        status_code: int,
        headers: dict,
        body: str,
    ) -> dict | None:
        if status_code != 200 or not body:
            return None

        data = body.encode("utf-8", errors="replace")
        h = hashlib.sha256(data).hexdigest()[:16]

        # Layer 1: exact hash match with baseline
        if self._baseline_hash and h == self._baseline_hash:
            return {"type": "soft404", "method": "hash_match"}

        # Layer 2: size similarity + keyword check
        if self._baseline_size:
            size_ratio = len(data) / max(self._baseline_size, 1)
            if 0.8 < size_ratio < 1.2:
                body_lower = body.lower()
                for kw in _SOFT404_KEYWORDS:
                    if kw in body_lower:
                        return {"type": "soft404", "method": "size_keyword",
                                "keyword": kw}

        # Layer 3: title keyword check
        title_match = _TITLE_RE.search(body)
        if title_match:
            title = title_match.group(1).lower().strip()
            for kw in ("404", "not found", "page not found"):
                if kw in title:
                    return {"type": "soft404", "method": "title", "keyword": kw}

        return None


# ---------------------------------------------------------------------------
# WordPressDetector
# ---------------------------------------------------------------------------


class WordPressDetector(BaseDetector):
    """Detect WordPress-powered websites."""

    name = "wordpress"

    _WP_SIGNATURES = (
        "/wp-content/",
        "/wp-includes/",
        "/wp-json/",
        "wp-emoji-release.min.js",
        'name="generator" content="WordPress',
    )

    _WP_HEADER_LINKS = (
        "wp-json",
        "xmlrpc.php",
    )

    def detect(
        self,
        url: str,
        status_code: int,
        headers: dict,
        body: str,
    ) -> dict | None:
        # Check Link header
        link_header = headers.get("link", "")
        for sig in self._WP_HEADER_LINKS:
            if sig in link_header:
                return {"type": "wordpress", "method": "header"}

        # Check body signatures
        if body:
            for sig in self._WP_SIGNATURES:
                if sig in body:
                    return {"type": "wordpress", "method": "body",
                            "signature": sig}

        return None


# ---------------------------------------------------------------------------
# detect_all  – registry that runs every detector
# ---------------------------------------------------------------------------

ALL_DETECTORS: list[BaseDetector] = [
    CloudflareDetector(),
    SiteGroundDetector(),
    WAFDetector(),
    Soft404Detector(),
    WordPressDetector(),
]


def detect_all(
    url: str,
    status_code: int,
    headers: dict,
    body: str,
) -> list[dict]:
    """Run every registered detector and return a list of matches."""
    results: list[dict] = []
    for detector in ALL_DETECTORS:
        try:
            result = detector.detect(url, status_code, headers, body)
            if result is not None:
                results.append(result)
        except Exception:
            pass
    return results


__all__ = [
    "detect_all",
    "BaseDetector",
    "CloudflareDetector",
    "SiteGroundDetector",
    "WAFDetector",
    "Soft404Detector",
    "WordPressDetector",
    "ALL_DETECTORS",
    "WAF_SIGNATURES",
]
